// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdjS8Nnu8McIzu0UZzOc5HbCPyXq67mcI',
    appId: '1:248223733643:web:5e620028c311f8b736018e',
    messagingSenderId: '248223733643',
    projectId: 'fbook-3ddfa',
    authDomain: 'fbook-3ddfa.firebaseapp.com',
    storageBucket: 'fbook-3ddfa.firebasestorage.app',
    measurementId: 'G-3D5PKCRD0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzpYhwiQrpsmH8CsBtqCu9rQniCKnx3uc',
    appId: '1:248223733643:android:43b68adb128ada8636018e',
    messagingSenderId: '248223733643',
    projectId: 'fbook-3ddfa',
    storageBucket: 'fbook-3ddfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn_zVbxzx1xmnbqCT777Du8AYUd8wals8',
    appId: '1:248223733643:ios:df33bbdb8ab3d72736018e',
    messagingSenderId: '248223733643',
    projectId: 'fbook-3ddfa',
    storageBucket: 'fbook-3ddfa.firebasestorage.app',
    iosBundleId: 'com.example.bookReminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn_zVbxzx1xmnbqCT777Du8AYUd8wals8',
    appId: '1:248223733643:ios:df33bbdb8ab3d72736018e',
    messagingSenderId: '248223733643',
    projectId: 'fbook-3ddfa',
    storageBucket: 'fbook-3ddfa.firebasestorage.app',
    iosBundleId: 'com.example.bookReminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdjS8Nnu8McIzu0UZzOc5HbCPyXq67mcI',
    appId: '1:248223733643:web:9f4413023e911c3036018e',
    messagingSenderId: '248223733643',
    projectId: 'fbook-3ddfa',
    authDomain: 'fbook-3ddfa.firebaseapp.com',
    storageBucket: 'fbook-3ddfa.firebasestorage.app',
    measurementId: 'G-JJXKKJ9DBQ',
  );
}
